"""add-tablas-proyecto2

Revision ID: 71f5cffcbdcf
Revises: 
Create Date: 2025-06-03 10:12:21.452549

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '71f5cffcbdcf'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artistas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=True),
    sa.Column('usuario', sa.String(length=50), nullable=True),
    sa.Column('correo', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('correo'),
    sa.UniqueConstraint('usuario')
    )
    op.create_table('disciplinas',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('productos',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('descripcion', sa.String(length=1000), nullable=True),
    sa.Column('precio', sa.Integer(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('artista_disciplinas',
    sa.Column('id_artista', sa.Integer(), nullable=False),
    sa.Column('id_disciplina', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['id_artista'], ['artistas.id'], ),
    sa.ForeignKeyConstraint(['id_disciplina'], ['disciplinas.id'], ),
    sa.PrimaryKeyConstraint('id_artista', 'id_disciplina')
    )
    op.create_table('publicaciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_artista', sa.Integer(), nullable=True),
    sa.Column('titulo', sa.String(length=255), nullable=True),
    sa.Column('contenido', sa.String(length=1000), nullable=True),
    sa.Column('fecha_publicacion', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_artista'], ['artistas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('publicaciones_tienda',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_artista', sa.Integer(), nullable=True),
    sa.Column('id_producto', sa.Integer(), nullable=True),
    sa.Column('nombre_producto', sa.String(length=255), nullable=True),
    sa.Column('descripcion', sa.String(length=1000), nullable=True),
    sa.Column('precio', sa.Integer(), nullable=True),
    sa.Column('stock', sa.Integer(), nullable=True),
    sa.Column('fecha_publicacion', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_artista'], ['artistas.id'], ),
    sa.ForeignKeyConstraint(['id_producto'], ['productos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reacciones',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('id_publicacion', sa.Integer(), nullable=True),
    sa.Column('id_usuario', sa.Integer(), nullable=True),
    sa.Column('tipo_reaccion', sa.String(length=20), nullable=False),
    sa.Column('comentario', sa.String(length=1000), nullable=True),
    sa.Column('fecha_reaccion', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['id_publicacion'], ['publicaciones.id'], ),
    sa.ForeignKeyConstraint(['id_usuario'], ['artistas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reacciones')
    op.drop_table('publicaciones_tienda')
    op.drop_table('publicaciones')
    op.drop_table('artista_disciplinas')
    op.drop_table('productos')
    op.drop_table('disciplinas')
    op.drop_table('artistas')
    # ### end Alembic commands ###
